# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Documentation: https://docs.brew.sh/Formula-Cookbook

class Kxconfig < Formula
  desc "Bash tools to manage multiple Kubernetes kubeconfigs organized by project"
  homepage "https://github.com/nunoarmada/kxconfig"
  url "https://github.com/nunoarmada/kxconfig/archive/refs/tags/v1.3.0.tar.gz"
  sha256 "d5558cd419c8d46bdc958064cb97f963d1ea793866414c025906ec15033512ed" # Update this after creating the first release
  license "MIT"
  head "https://github.com/nunoarmada/kxconfig.git", branch: "main"

  depends_on "bash"
  depends_on "kubectl" => :recommended

  def install
    # Install kxconfig
    bin.install "bin/kxconfig"
    # Install kxswap
    bin.install "bin/kxswap"
    # Install bash completion
    bash_completion.install "completions/kxconfig-completion.bash" => "kxconfig"
  end

  test do
    # Test kxconfig help
    assert_match "Usage:", shell_output("#{bin}/kxconfig --help", 1)
    # Test kxswap help
    assert_match "Usage:", shell_output("#{bin}/kxswap --help", 1)
  end
end
