# typed: false
# frozen_string_literal: true

# This file was generated by the Homebrew formula generator.
# Documentation: https://docs.brew.sh/Formula-Cookbook

class Kxconfig < Formula
  desc "Bash tools to manage multiple Kubernetes kubeconfigs organized by project"
  homepage "https://github.com/nunoarmada/kxconfig"
  url "https://github.com/nunoarmada/kxconfig/archive/refs/tags/kxconfig-v1.6.0.tar.gz"
  sha256 "c9b290dfb434df2f5ba9a6284ee2e725f0765d82fea432cbbf8ebe63218916cb"
  license "MIT"
  head "https://github.com/nunoarmada/kxconfig.git", branch: "main"

  depends_on "bash"
  depends_on "kubectl" => :recommended

  def install
    # Install kxconfig
    bin.install "bin/kxconfig"
    # Install kxswap
    bin.install "bin/kxswap"
    # Install bash completion
    bash_completion.install "completions/kxconfig-completion.bash" => "kxconfig"
  end

  test do
    # Test kxconfig help
    assert_match "Usage:", shell_output("#{bin}/kxconfig --help", 1)
    # Test kxswap help
    assert_match "Usage:", shell_output("#{bin}/kxswap --help", 1)
  end
end
